# -*- coding: utf-8 -*-
# vim: ft=yaml
#
# Set values specific to:
#   salt['config.get']('os_family') == Debian.
#
# You just need to add the key:values for this `os_family` that differ
# from `defaults.yaml` + `<osarch>.yaml`.
#
# If you do not need to provide defaults via the `os_family` config,
# you can remove this file or provide at least an empty dict, e.g.
# values: {}
---
values:
  pkg:
    use_upstream_repo: true
    repo:
      humanname: grafana_official
      name: deb https://packages.grafana.com/oss/deb stable main
      file: /etc/apt/sources.list.d/grafana.list
      key_url: https://packages.grafana.com/gpg.key
...
