# -*- coding: utf-8 -*-
# vim: ft=yaml
---
values:
  enabled: true
  version: "9.2.0"       # "enterprise_9.2.0"

  # rootgroup: root
  # group_gid
  # user_uid

  user: grafana
  group: grafana
  bin_dir: /opt/grafana
  data_dir: /var/lib/grafana
  config_dir: /etc/grafana
  config_file: grafana.ini

  service:
    enabled: true
    name: grafana-server

  pkg:
    name: grafana
    binary: grafana
    use_upstream_repo: true
    repo:
      humanname: grafana
      name: grafana
      comments:
        - installed by salt

  config: {}
  ldap: {}

  environ_file: /etc/default/grafana.sh
  environ: []

  tofs:
    # The files_switch key serves as a selector for alternative
    # directories under the formula files directory. See TOFS pattern
    # doc for more info.
    # Note: Any value not evaluated by `config.get` will be used literally.
    # This can be used to set custom paths, as many levels deep as required.
    files_switch:
      - any/path/can/be/used/here
      - id
      - osfinger
      - os
      - os_family
    # All aspects of path/file resolution are customisable using the options below.
    # This is unnecessary in most cases; there are sensible defaults.
    # path_prefix: grafana_alt
    # dirs:
    #   files: files_alt
    #   default: default_alt
    source_files:
      grafana-config-files:
        - 'alt_grafana.ini.jinja'
      grafana-environ-files:
        - 'alt_grafana.sh.jinja'
      grafana-ldap-files:
        - 'ldap.toml'
