# -*- coding: utf-8 -*-
# vim: ft=yaml
---
values:
  enabled: true
  version: "9.2.0"       # "enterprise_9.2.0"

  # Setup system user
  name: grafana
  user: grafana
  group: grafana
  # rootgroup: root
  # group_gid
  # user_uid
  bin_dir: /opt/grafana

  pkg:
    name: grafana
    binary: grafana
    use_upstream_archive: false
    use_upstream_repo: false
    repo:
      humanname: grafana
      name: grafana
      comments:
        - installed by salt
      enabled: 1
      gpgcheck: 1
    archive:
      name: /opt
      uri: https://dl.grafana.com/oss/release
      source: None
      source_hash: None
      trim_output: true  # works in 2018.3.2. onwards
      archive_suffix: tar.gz
      archive_format: tar
      enforce_toplevel: false          # needed for grafana
      options: '--strip-components=1'  # needed for grafana

  # Provided in `map.jinja` via. `grains.kernel`
  kernel: ''
  config_file: /etc/grafana/grafana.ini
  config: {}
  environ_file: /etc/default/grafana.sh
  environ: []


  linux:
    # 'Alternatives system' priority: zero disables (default)
    altpriority: 0
